"""moved_auth_to_a_separate_service

Revision ID: 938b464628e1
Revises: 3a24e8e2f37a
Create Date: 2025-10-04 17:58:39.842656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '938b464628e1'
down_revision: Union[str, Sequence[str], None] = '3a24e8e2f37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('directories_user_id_fkey'), 'directories', type_='foreignkey')
    op.drop_constraint(op.f('texts_user_id_fkey'), 'texts', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('texts_user_id_fkey'), 'texts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('directories_user_id_fkey'), 'directories', 'users', ['user_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tg_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('id', name=op.f('users_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
