"""Delete TgUsers

Revision ID: f3f682c89529
Revises: 41e95d8a32d6
Create Date: 2025-09-14 19:26:50.624303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f682c89529'
down_revision: Union[str, Sequence[str], None] = '41e95d8a32d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_users')
    op.create_unique_constraint(None, 'cards', ['id'])
    op.create_unique_constraint(None, 'directories', ['id'])
    op.create_unique_constraint(None, 'texts', ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tg_username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tg_username')
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'texts', type_='unique')
    op.drop_constraint(None, 'directories', type_='unique')
    op.drop_constraint(None, 'cards', type_='unique')
    op.create_table('tg_users',
    sa.Column('tg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tg_users_user_id_fkey')),
    sa.PrimaryKeyConstraint('tg_id', name=op.f('tg_users_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('tg_users_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
